title: Movie Reviews by stuffwithevan
description: > # this means to ignore newlines until "baseurl:"
  Evan loves movies and watches them all the time. This blog is basically just his
  thoughts on these movies typed out for everyone to see.
permalink: ':title/'
baseurl: ""
url: "http://movies.stuffwithevan.com"
site-twitter: stuffwithevan

repository: oakeef/oakeef.github.io

# Author Settings
author: Evan
author-img: 6433506.jpeg
about-author: I watch a lot of movies and wanted to start keeping track of my thoughts on them.
facebook: # add your Facebook handle
twitter: stuffwithevan
github: oakeef # add your Github handle
linkedin: # add your Linkedin handle
email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
