title: Movie Reviews by stuffwithevan
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: ""
url: "http://movies.stuffwithevan.com"
site-twitter: stuffwithevan

repository: oakeef/oakeef.github.io

# Author Settings
author: Evan
author-img: 6433506.jpeg
about-author: Evan is a big movie fan and he usually has a bunch of thoughts about movies. This site is made to put those thoughts out there.
facebook: # add your Facebook handle
github: oakeef # add your Github handle
linkedin: # add your Linkedin handle
email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
